//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_Senco_Admin.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class SENCO_DB_AdminEntities : DbContext
    {
        public SENCO_DB_AdminEntities()
            : base("name=SENCO_DB_AdminEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<tbl_admin_login> tbl_admin_login { get; set; }
        public DbSet<tbl_astrologer_appointment> tbl_astrologer_appointment { get; set; }
        public DbSet<tbl_astrologer_master> tbl_astrologer_master { get; set; }
        public DbSet<tbl_astrologer_schedule> tbl_astrologer_schedule { get; set; }
        public DbSet<tbl_astrologer_store_link> tbl_astrologer_store_link { get; set; }
        public DbSet<tbl_city_master> tbl_city_master { get; set; }
        public DbSet<tbl_Collections> tbl_Collections { get; set; }
        public DbSet<tbl_country_master> tbl_country_master { get; set; }
        public DbSet<tbl_dashboard_analytics> tbl_dashboard_analytics { get; set; }
        public DbSet<tbl_designer_appointment> tbl_designer_appointment { get; set; }
        public DbSet<tbl_ecommerce_transaction> tbl_ecommerce_transaction { get; set; }
        public DbSet<tbl_events> tbl_events { get; set; }
        public DbSet<tbl_gold_price> tbl_gold_price { get; set; }
        public DbSet<tbl_horoscope_banner> tbl_horoscope_banner { get; set; }
        public DbSet<tbl_horoscope_master> tbl_horoscope_master { get; set; }
        public DbSet<tbl_horoscope_pricing> tbl_horoscope_pricing { get; set; }
        public DbSet<tbl_horoscope_purchases> tbl_horoscope_purchases { get; set; }
        public DbSet<tbl_horoscope_purchases_attempts> tbl_horoscope_purchases_attempts { get; set; }
        public DbSet<tbl_horoscope_schedule> tbl_horoscope_schedule { get; set; }
        public DbSet<tbl_horoscope_testimonials> tbl_horoscope_testimonials { get; set; }
        public DbSet<tbl_manage_video_audiance_location> tbl_manage_video_audiance_location { get; set; }
        public DbSet<tbl_manage_videos> tbl_manage_videos { get; set; }
        public DbSet<tbl_mobile_verification_status> tbl_mobile_verification_status { get; set; }
        public DbSet<tbl_offer_notification_schedule> tbl_offer_notification_schedule { get; set; }
        public DbSet<tbl_offers> tbl_offers { get; set; }
        public DbSet<tbl_offers_audiance_location> tbl_offers_audiance_location { get; set; }
        public DbSet<tbl_purchase_appointment> tbl_purchase_appointment { get; set; }
        public DbSet<tbl_push_notification> tbl_push_notification { get; set; }
        public DbSet<tbl_scan_instruction> tbl_scan_instruction { get; set; }
        public DbSet<tbl_scan_queries> tbl_scan_queries { get; set; }
        public DbSet<tbl_scan_url> tbl_scan_url { get; set; }
        public DbSet<tbl_senco_synchronization> tbl_senco_synchronization { get; set; }
        public DbSet<tbl_spotlight> tbl_spotlight { get; set; }
        public DbSet<tbl_state_master> tbl_state_master { get; set; }
        public DbSet<tbl_store_call_log> tbl_store_call_log { get; set; }
        public DbSet<tbl_store_master> tbl_store_master { get; set; }
        public DbSet<tbl_store_offer_views> tbl_store_offer_views { get; set; }
        public DbSet<tbl_store_offers> tbl_store_offers { get; set; }
        public DbSet<tbl_store_photos> tbl_store_photos { get; set; }
        public DbSet<tbl_store_reviews> tbl_store_reviews { get; set; }
        public DbSet<tbl_swarna_scheme_creation_details> tbl_swarna_scheme_creation_details { get; set; }
        public DbSet<tbl_swarna_user_registration> tbl_swarna_user_registration { get; set; }
        public DbSet<tbl_swarna_yojna> tbl_swarna_yojna { get; set; }
        public DbSet<tbl_swarna_yojna_payment_history> tbl_swarna_yojna_payment_history { get; set; }
        public DbSet<tbl_tax_percentage> tbl_tax_percentage { get; set; }
        public DbSet<tbl_temp_ecommerce_payment_gateway> tbl_temp_ecommerce_payment_gateway { get; set; }
        public DbSet<tbl_temp_paymentgateway> tbl_temp_paymentgateway { get; set; }
        public DbSet<tbl_temp_swarna_paymentgateway> tbl_temp_swarna_paymentgateway { get; set; }
        public DbSet<tbl_user_details> tbl_user_details { get; set; }
        public DbSet<tbl_version_master> tbl_version_master { get; set; }
        public DbSet<tbl_zonal_manager> tbl_zonal_manager { get; set; }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    }
}
