//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_Senco_Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_dashboard_analytics
    {
        public int DashBoardAnalytics_id { get; set; }
        public string video_click { get; set; }
        public string offer_click { get; set; }
        public string spotlight_click { get; set; }
        public string collection_click { get; set; }
        public string event_click { get; set; }
        public string registration_data { get; set; }
        public string appoitment_category_data { get; set; }
        public string active_uninstall_data { get; set; }
        public string purchase_app_data { get; set; }
        public string designer_app_data { get; set; }
        public string astrologer_app_data { get; set; }
        public string sales_list_data { get; set; }
        public string emi_sales_data { get; set; }
        public string astro_sales_data { get; set; }
    }
}
