//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_Senco_Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_horoscope_purchases
    {
        public int order_no { get; set; }
        public Nullable<System.DateTime> order_date { get; set; }
        public string user_name { get; set; }
        public string mobile_no { get; set; }
        public string email_address { get; set; }
        public int city { get; set; }
        public int country { get; set; }
        public string purchase_details { get; set; }
        public Nullable<byte> status { get; set; }
        public string order_id { get; set; }
        public int product_code { get; set; }
        public string payment_ref_no { get; set; }
        public string file_name { get; set; }
        public Nullable<int> user_no { get; set; }
        public string pdf_file { get; set; }
        public string appointment_day { get; set; }
        public Nullable<System.DateTime> appointment_date { get; set; }
        public string appointment_time { get; set; }
        public Nullable<int> astrologer_id { get; set; }
        public string gender { get; set; }
        public string consultation_type { get; set; }
    
        public virtual tbl_city_master tbl_city_master { get; set; }
        public virtual tbl_country_master tbl_country_master { get; set; }
        public virtual tbl_horoscope_pricing tbl_horoscope_pricing { get; set; }
    }
}
