//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_Senco_Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_version_master
    {
        public int version_id { get; set; }
        public decimal version { get; set; }
        public string store { get; set; }
        public string InventLocationId { get; set; }
        public string swarnyojna_view { get; set; }
        public string time_spent { get; set; }
        public string swarnyojna_schemecreation { get; set; }
    }
}
