//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_Senco_Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_swarna_scheme_creation_details
    {
        public int scheme_reg_id { get; set; }
        public Nullable<int> scheme_member_id { get; set; }
        public string scheme_payload { get; set; }
        public Nullable<System.DateTime> created_on { get; set; }
    }
}
