//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_Senco_Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_swarna_yojna
    {
        public tbl_swarna_yojna()
        {
            this.tbl_swarna_yojna_payment_history = new HashSet<tbl_swarna_yojna_payment_history>();
        }
    
        public int sy_no { get; set; }
        public int user_no { get; set; }
        public string current_plan_no { get; set; }
        public string current_plan_title { get; set; }
        public string current_plan_details { get; set; }
        public Nullable<System.DateTime> plan_start_date { get; set; }
        public Nullable<System.DateTime> plan_end_date { get; set; }
        public Nullable<System.DateTime> next_payment_date { get; set; }
        public Nullable<decimal> next_payment_amount { get; set; }
        public Nullable<System.DateTime> last_payment_date { get; set; }
        public Nullable<decimal> last_payment_amount { get; set; }
        public string image_path { get; set; }
        public bool is_active { get; set; }
        public decimal monthly_emi { get; set; }
    
        public virtual ICollection<tbl_swarna_yojna_payment_history> tbl_swarna_yojna_payment_history { get; set; }
        public virtual tbl_user_details tbl_user_details { get; set; }
    }
}
