//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_Senco_Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_swarna_yojna_payment_history
    {
        public int syph_no { get; set; }
        public int sy_no { get; set; }
        public Nullable<System.DateTime> syph_date { get; set; }
        public Nullable<decimal> syph_amount { get; set; }
        public string payment_reference_id { get; set; }
    
        public virtual tbl_swarna_yojna tbl_swarna_yojna { get; set; }
    }
}
