//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_Senco_Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_city_master
    {
        public tbl_city_master()
        {
            this.tbl_gold_price = new HashSet<tbl_gold_price>();
            this.tbl_horoscope_purchases = new HashSet<tbl_horoscope_purchases>();
            this.tbl_manage_video_audiance_location = new HashSet<tbl_manage_video_audiance_location>();
            this.tbl_offers_audiance_location = new HashSet<tbl_offers_audiance_location>();
            this.tbl_store_master = new HashSet<tbl_store_master>();
            this.tbl_user_details = new HashSet<tbl_user_details>();
            this.tbl_scan_url = new HashSet<tbl_scan_url>();
        }
    
        public int city_no { get; set; }
        public string city_name { get; set; }
        public int country_no { get; set; }
        public string city_geo_coordinates { get; set; }
        public string city_geo_radius { get; set; }
        public Nullable<bool> is_active { get; set; }
        public Nullable<int> state_no { get; set; }
    
        public virtual tbl_country_master tbl_country_master { get; set; }
        public virtual tbl_state_master tbl_state_master { get; set; }
        public virtual ICollection<tbl_gold_price> tbl_gold_price { get; set; }
        public virtual ICollection<tbl_horoscope_purchases> tbl_horoscope_purchases { get; set; }
        public virtual ICollection<tbl_manage_video_audiance_location> tbl_manage_video_audiance_location { get; set; }
        public virtual ICollection<tbl_offers_audiance_location> tbl_offers_audiance_location { get; set; }
        public virtual ICollection<tbl_store_master> tbl_store_master { get; set; }
        public virtual ICollection<tbl_user_details> tbl_user_details { get; set; }
        public virtual ICollection<tbl_scan_url> tbl_scan_url { get; set; }
    }
}
