//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_Senco_Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_mobile_verification_status
    {
        public int mobile_ver_id { get; set; }
        public Nullable<int> mobile_ver_user_id { get; set; }
        public Nullable<System.DateTime> mobile_ver_datetime { get; set; }
        public Nullable<bool> mobile_ver_status { get; set; }
    }
}
