//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_Senco_Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_horoscope_schedule
    {
        public int hs_no { get; set; }
        public int horoscope_no { get; set; }
        public Nullable<System.DateTime> schedule_from_date { get; set; }
        public Nullable<System.DateTime> schedule_to_date { get; set; }
        public string horoscope_schedule_description { get; set; }
        public Nullable<bool> is_active { get; set; }
        public string Today_Prediction { get; set; }
        public string Today_Lucky_Color { get; set; }
        public string Today_Lucky_Number { get; set; }
        public string Today_Lucky_Time { get; set; }
        public string health_per { get; set; }
        public string health_desc { get; set; }
        public string love_per { get; set; }
        public string love_desc { get; set; }
        public string career_per { get; set; }
        public string career_desc { get; set; }
    
        public virtual tbl_horoscope_master tbl_horoscope_master { get; set; }
    }
}
