//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_Senco_Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_horoscope_master
    {
        public tbl_horoscope_master()
        {
            this.tbl_horoscope_schedule = new HashSet<tbl_horoscope_schedule>();
            this.tbl_user_details = new HashSet<tbl_user_details>();
        }
    
        public int horoscope_no { get; set; }
        public string horoscope_name { get; set; }
        public string horoscope_logo { get; set; }
        public Nullable<System.DateTime> horoscope_birthdate_from { get; set; }
        public Nullable<System.DateTime> horoscope_birthdate_to { get; set; }
        public string horoscope_description { get; set; }
    
        public virtual ICollection<tbl_horoscope_schedule> tbl_horoscope_schedule { get; set; }
        public virtual ICollection<tbl_user_details> tbl_user_details { get; set; }
    }
}
