//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_Senco_Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_user_details
    {
        public tbl_user_details()
        {
            this.tbl_astrologer_appointment = new HashSet<tbl_astrologer_appointment>();
            this.tbl_designer_appointment = new HashSet<tbl_designer_appointment>();
            this.tbl_purchase_appointment = new HashSet<tbl_purchase_appointment>();
            this.tbl_scan_queries = new HashSet<tbl_scan_queries>();
            this.tbl_store_call_log = new HashSet<tbl_store_call_log>();
            this.tbl_store_offer_views = new HashSet<tbl_store_offer_views>();
            this.tbl_store_reviews = new HashSet<tbl_store_reviews>();
            this.tbl_swarna_yojna = new HashSet<tbl_swarna_yojna>();
            this.tbl_temp_ecommerce_payment_gateway = new HashSet<tbl_temp_ecommerce_payment_gateway>();
        }
    
        public int user_no { get; set; }
        public string user_uid { get; set; }
        public string user_name { get; set; }
        public string user_mobile_no { get; set; }
        public Nullable<bool> is_mobile_verified { get; set; }
        public Nullable<bool> is_active { get; set; }
        public Nullable<int> user_current_country { get; set; }
        public Nullable<int> user_current_city { get; set; }
        public string user_last_geocoordinates { get; set; }
        public Nullable<System.DateTime> user_birth_date { get; set; }
        public Nullable<System.DateTime> user_birth_time { get; set; }
        public string user_birth_location { get; set; }
        public Nullable<int> horoscope_no { get; set; }
        public Nullable<decimal> current_reward_points { get; set; }
        public Nullable<byte> user_gender { get; set; }
        public string device_token { get; set; }
        public string user_email { get; set; }
        public Nullable<decimal> app_version { get; set; }
        public string user_photo { get; set; }
        public Nullable<System.DateTime> last_use_app_datetime { get; set; }
        public Nullable<System.DateTime> user_registred_on { get; set; }
        public Nullable<bool> uninstall_status_flag { get; set; }
        public string IMEI_number { get; set; }
        public Nullable<System.DateTime> uninstall_datetime { get; set; }
        public Nullable<int> sms_count { get; set; }
        public Nullable<int> mobile_verification_count { get; set; }
        public Nullable<bool> mobile_verification_completed { get; set; }
    
        public virtual ICollection<tbl_astrologer_appointment> tbl_astrologer_appointment { get; set; }
        public virtual tbl_city_master tbl_city_master { get; set; }
        public virtual tbl_country_master tbl_country_master { get; set; }
        public virtual ICollection<tbl_designer_appointment> tbl_designer_appointment { get; set; }
        public virtual tbl_horoscope_master tbl_horoscope_master { get; set; }
        public virtual ICollection<tbl_purchase_appointment> tbl_purchase_appointment { get; set; }
        public virtual ICollection<tbl_scan_queries> tbl_scan_queries { get; set; }
        public virtual ICollection<tbl_store_call_log> tbl_store_call_log { get; set; }
        public virtual ICollection<tbl_store_offer_views> tbl_store_offer_views { get; set; }
        public virtual ICollection<tbl_store_reviews> tbl_store_reviews { get; set; }
        public virtual ICollection<tbl_swarna_yojna> tbl_swarna_yojna { get; set; }
        public virtual ICollection<tbl_temp_ecommerce_payment_gateway> tbl_temp_ecommerce_payment_gateway { get; set; }
    }
}
