//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_Senco_Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_offer_notification_schedule
    {
        public int offer_ns_no { get; set; }
        public int offer_no { get; set; }
        public Nullable<System.DateTime> notification_start_date { get; set; }
        public Nullable<System.DateTime> notification_end_date { get; set; }
        public string days_of_week { get; set; }
        public string times_of_day { get; set; }
    
        public virtual tbl_offers tbl_offers { get; set; }
    }
}
