//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_Senco_Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_temp_swarna_paymentgateway
    {
        public int temp_swarna_yojna_id { get; set; }
        public string temp_swarna_bankauthorizationid { get; set; }
        public string temp_swarna_banktransactionid { get; set; }
        public string temp_swarna_customer_code { get; set; }
        public string temp_swarna_customer_name { get; set; }
        public Nullable<int> temp_swarna_inventlocation_id { get; set; }
        public Nullable<int> temp_swarna_linenum { get; set; }
        public Nullable<decimal> temp_swarna_payamount { get; set; }
        public Nullable<System.DateTime> temp_swarna_paymentdate { get; set; }
        public string temp_swarna_paymententryno { get; set; }
        public string temp_swarna_paymentmonth { get; set; }
        public string temp_swarna_payment_type { get; set; }
        public string temp_swarna_payment_year { get; set; }
        public string temp_swarna_payment_schemeentryno { get; set; }
        public string temp_swarna_store { get; set; }
        public string temp_swarna_tender_type { get; set; }
        public string temp_swarna_transaction_id { get; set; }
        public Nullable<int> temp_swarna_member_id { get; set; }
        public string temp_swarna_mobile_no { get; set; }
        public string temp_swarna_order_no { get; set; }
        public string temp_swarna_member_email { get; set; }
        public string ttemp_swarna_payment_scheme_code { get; set; }
        public string temp_swarna_payment_reciept { get; set; }
        public Nullable<bool> temp_payment_status { get; set; }
        public Nullable<int> temp_swarna_tenure { get; set; }
        public string temp_swarna_payload_json { get; set; }
        public Nullable<int> temp_swarna_current_emi_no { get; set; }
        public string response_message { get; set; }
        public Nullable<int> response_code { get; set; }
    }
}
