//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_Senco_Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_horoscope_pricing
    {
        public tbl_horoscope_pricing()
        {
            this.tbl_horoscope_purchases = new HashSet<tbl_horoscope_purchases>();
        }
    
        public int product_code { get; set; }
        public string product_title { get; set; }
        public Nullable<int> discount { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<int> without_gst_amount { get; set; }
        public Nullable<int> gst_amount { get; set; }
        public Nullable<bool> is_active { get; set; }
    
        public virtual ICollection<tbl_horoscope_purchases> tbl_horoscope_purchases { get; set; }
    }
}
