//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_Senco_Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_scan_queries
    {
        public int query_id { get; set; }
        public int user_id { get; set; }
        public string lat { get; set; }
        public Nullable<System.DateTime> datetime { get; set; }
        public string city_name { get; set; }
        public string longitute { get; set; }
        public string scan_logo { get; set; }
    
        public virtual tbl_user_details tbl_user_details { get; set; }
    }
}
