//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_Senco_Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_manage_videos
    {
        public tbl_manage_videos()
        {
            this.tbl_manage_video_audiance_location = new HashSet<tbl_manage_video_audiance_location>();
        }
    
        public int managevideo_id { get; set; }
        public string managevideo_name { get; set; }
        public string managevideo_image { get; set; }
        public string managevideo_video_url { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<System.DateTime> updated_on { get; set; }
        public Nullable<int> clicks { get; set; }
    
        public virtual ICollection<tbl_manage_video_audiance_location> tbl_manage_video_audiance_location { get; set; }
    }
}
