//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_Senco_Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_horoscope_purchases_attempts
    {
        public int attempt_no { get; set; }
        public string user_name { get; set; }
        public string user_mobile_no { get; set; }
        public string user_city_name { get; set; }
        public Nullable<System.DateTime> birth_date { get; set; }
        public string horoscope_name { get; set; }
        public string gender { get; set; }
        public Nullable<System.DateTime> on_attempted_date { get; set; }
        public string code { get; set; }
        public string product_name { get; set; }
    }
}
