//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_Senco_Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_temp_ecommerce_payment_gateway
    {
        public int temp_ecommerce_id { get; set; }
        public Nullable<int> temp_ecommerce_user_id { get; set; }
        public string temp_ecommerce_user_name { get; set; }
        public string temp_ecommerce_user_email { get; set; }
        public string temp_ecommerce_user_mobile_no { get; set; }
        public Nullable<decimal> temp_ecommerce_pay_amount { get; set; }
        public string temp_ecommerce_product_details { get; set; }
        public string temp_ecommerce_order_no { get; set; }
        public Nullable<bool> temp_ecommerce_payment_status { get; set; }
        public Nullable<System.DateTime> temp_ecommerce_payment_date { get; set; }
        public Nullable<System.DateTime> temp_ecommerce_order_date { get; set; }
    
        public virtual tbl_user_details tbl_user_details { get; set; }
    }
}
