//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_Senco_Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_store_photos
    {
        public int store_photo_no { get; set; }
        public int store_no { get; set; }
        public string store_photo_thumbnail { get; set; }
        public string store_photo_full_image { get; set; }
        public Nullable<int> store_photo_sequence { get; set; }
    
        public virtual tbl_store_master tbl_store_master { get; set; }
    }
}
