//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_Senco_Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_senco_synchronization
    {
        public int senco_sync_id { get; set; }
        public string senco_sync_name { get; set; }
        public string senco_sync_email { get; set; }
        public string senco_sync_mobile_no { get; set; }
        public Nullable<int> senco_sync_user_id { get; set; }
        public Nullable<System.DateTime> sync_date_time { get; set; }
    }
}
