//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_Senco_Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_offers
    {
        public tbl_offers()
        {
            this.tbl_offer_notification_schedule = new HashSet<tbl_offer_notification_schedule>();
            this.tbl_offers_audiance_location = new HashSet<tbl_offers_audiance_location>();
            this.tbl_store_offers = new HashSet<tbl_store_offers>();
        }
    
        public int offer_no { get; set; }
        public string offer_name { get; set; }
        public string offer_banner_thumbnail { get; set; }
        public string offer_full_banner { get; set; }
        public Nullable<int> offer_redirect_to_shop_or_web { get; set; }
        public string web_url { get; set; }
        public Nullable<System.DateTime> offer_created_on { get; set; }
        public Nullable<System.DateTime> offer_expires_on { get; set; }
        public Nullable<int> offer_totalclick_count { get; set; }
        public Nullable<bool> is_active { get; set; }
        public string offer_desc { get; set; }
        public Nullable<bool> is_new_arrival { get; set; }
        public Nullable<bool> is_event { get; set; }
    
        public virtual ICollection<tbl_offer_notification_schedule> tbl_offer_notification_schedule { get; set; }
        public virtual ICollection<tbl_offers_audiance_location> tbl_offers_audiance_location { get; set; }
        public virtual ICollection<tbl_store_offers> tbl_store_offers { get; set; }
    }
}
