//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_Senco_Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_state_master
    {
        public tbl_state_master()
        {
            this.tbl_city_master = new HashSet<tbl_city_master>();
            this.tbl_designer_appointment = new HashSet<tbl_designer_appointment>();
        }
    
        public int state_no { get; set; }
        public string state_name { get; set; }
        public Nullable<bool> is_active { get; set; }
        public int country_no { get; set; }
    
        public virtual ICollection<tbl_city_master> tbl_city_master { get; set; }
        public virtual tbl_country_master tbl_country_master { get; set; }
        public virtual ICollection<tbl_designer_appointment> tbl_designer_appointment { get; set; }
    }
}
