//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_Senco_Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_store_master
    {
        public tbl_store_master()
        {
            this.tbl_astrologer_appointment = new HashSet<tbl_astrologer_appointment>();
            this.tbl_astrologer_store_link = new HashSet<tbl_astrologer_store_link>();
            this.tbl_designer_appointment = new HashSet<tbl_designer_appointment>();
            this.tbl_purchase_appointment = new HashSet<tbl_purchase_appointment>();
            this.tbl_store_call_log = new HashSet<tbl_store_call_log>();
            this.tbl_store_offers = new HashSet<tbl_store_offers>();
            this.tbl_store_photos = new HashSet<tbl_store_photos>();
            this.tbl_store_reviews = new HashSet<tbl_store_reviews>();
        }
    
        public int store_no { get; set; }
        public string store_name { get; set; }
        public Nullable<int> store_city_no { get; set; }
        public string store_address { get; set; }
        public string store_pincode { get; set; }
        public string store_geo_coordinates { get; set; }
        public string store_contact_person { get; set; }
        public string store_contact_person_mobile_no { get; set; }
        public string store_contact_nos { get; set; }
        public string working_timing { get; set; }
        public string branch_code { get; set; }
        public Nullable<decimal> gold_price { get; set; }
        public string store_emai_id { get; set; }
        public string store_email_id { get; set; }
    
        public virtual ICollection<tbl_astrologer_appointment> tbl_astrologer_appointment { get; set; }
        public virtual ICollection<tbl_astrologer_store_link> tbl_astrologer_store_link { get; set; }
        public virtual tbl_city_master tbl_city_master { get; set; }
        public virtual ICollection<tbl_designer_appointment> tbl_designer_appointment { get; set; }
        public virtual ICollection<tbl_purchase_appointment> tbl_purchase_appointment { get; set; }
        public virtual ICollection<tbl_store_call_log> tbl_store_call_log { get; set; }
        public virtual ICollection<tbl_store_offers> tbl_store_offers { get; set; }
        public virtual ICollection<tbl_store_photos> tbl_store_photos { get; set; }
        public virtual ICollection<tbl_store_reviews> tbl_store_reviews { get; set; }
    }
}
