//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_Senco_Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_gold_price
    {
        public int gold_price_no { get; set; }
        public int city_no { get; set; }
        public Nullable<System.DateTime> validity_start_date { get; set; }
        public Nullable<System.DateTime> validity_end_date { get; set; }
        public string gold_price_value { get; set; }
        public Nullable<bool> is_active { get; set; }
        public string price_description { get; set; }
    
        public virtual tbl_city_master tbl_city_master { get; set; }
    }
}
