//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_Senco_Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ecommerce_transaction
    {
        public int ecommerce_id { get; set; }
        public Nullable<int> member_id { get; set; }
        public string payload { get; set; }
        public Nullable<System.DateTime> date_time { get; set; }
    }
}
