//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_Senco_Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_scan_url
    {
        public int scan_id { get; set; }
        public bool is_url { get; set; }
        public bool is_store { get; set; }
        public bool is_offer { get; set; }
        public string scan_description { get; set; }
        public string website { get; set; }
        public string store_offer_id { get; set; }
        public byte from_age { get; set; }
        public byte to_age { get; set; }
        public int city_no { get; set; }
        public string scan_logo { get; set; }
    
        public virtual tbl_city_master tbl_city_master { get; set; }
    }
}
