//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_Senco_Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_tax_percentage
    {
        public int tax_id { get; set; }
        public string cgst_per { get; set; }
        public string sgst_per { get; set; }
        public string igst_per { get; set; }
    }
}
