//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_Senco_Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_admin_login
    {
        public int admin_id { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public bool is_active { get; set; }
        public string name { get; set; }
    }
}
