//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_Senco_Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_offers_audiance_location
    {
        public int offer_al_no { get; set; }
        public int offer_no { get; set; }
        public int city_no { get; set; }
        public Nullable<int> offer_cityclick_count { get; set; }
    
        public virtual tbl_city_master tbl_city_master { get; set; }
        public virtual tbl_offers tbl_offers { get; set; }
    }
}
