//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_Senco_Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_horoscope_testimonials
    {
        public int horoscope_testimonial_id { get; set; }
        public string horoscope_testimonial_name { get; set; }
        public string horoscope_testimonial_description { get; set; }
        public string horoscope_testimonial_place { get; set; }
        public string horoscope_testimonial_photo { get; set; }
        public Nullable<System.DateTime> updated_on { get; set; }
        public Nullable<bool> status { get; set; }
    }
}
