//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_Senco_Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_temp_paymentgateway
    {
        public int payment_id { get; set; }
        public string order_id { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string member_id { get; set; }
        public Nullable<System.DateTime> order_date { get; set; }
        public string email { get; set; }
        public string service_option { get; set; }
        public string unique_code { get; set; }
        public string starsign { get; set; }
        public Nullable<System.DateTime> date_of_birth { get; set; }
        public string time_of_birth { get; set; }
        public string place_of_birth { get; set; }
        public string name { get; set; }
        public string appointment_day { get; set; }
        public Nullable<System.DateTime> appointment_date { get; set; }
        public string appointment_time { get; set; }
        public Nullable<int> astrologer_id { get; set; }
        public string gender { get; set; }
        public string consultation_type { get; set; }
        public Nullable<bool> temp_payment_status { get; set; }
    }
}
