//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_Senco_Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_country_master
    {
        public tbl_country_master()
        {
            this.tbl_city_master = new HashSet<tbl_city_master>();
            this.tbl_horoscope_purchases = new HashSet<tbl_horoscope_purchases>();
            this.tbl_state_master = new HashSet<tbl_state_master>();
            this.tbl_user_details = new HashSet<tbl_user_details>();
        }
    
        public int country_no { get; set; }
        public string country_name { get; set; }
        public Nullable<bool> is_active { get; set; }
    
        public virtual ICollection<tbl_city_master> tbl_city_master { get; set; }
        public virtual ICollection<tbl_horoscope_purchases> tbl_horoscope_purchases { get; set; }
        public virtual ICollection<tbl_state_master> tbl_state_master { get; set; }
        public virtual ICollection<tbl_user_details> tbl_user_details { get; set; }
    }
}
