//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_Senco_Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_manage_video_audiance_location
    {
        public int managevideo_al_no { get; set; }
        public int managevideo_id { get; set; }
        public int city_no { get; set; }
    
        public virtual tbl_city_master tbl_city_master { get; set; }
        public virtual tbl_manage_videos tbl_manage_videos { get; set; }
    }
}
