//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_Senco_Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_store_offers
    {
        public tbl_store_offers()
        {
            this.tbl_store_offer_views = new HashSet<tbl_store_offer_views>();
        }
    
        public int store_offer_no { get; set; }
        public int store_no { get; set; }
        public int offer_no { get; set; }
    
        public virtual tbl_offers tbl_offers { get; set; }
        public virtual tbl_store_master tbl_store_master { get; set; }
        public virtual ICollection<tbl_store_offer_views> tbl_store_offer_views { get; set; }
    }
}
